### ISSUE TITLE
Diagrams error: /bin/bash: plantuml: command not found 

### ISSUE THREAD

**Issue by WolfgangFahl** [samwilson/diagrams-extension#16]
the path to plantuml.jar used to be configurable in https://www.mediawiki.org/wiki/Extension:PlantUML - unfortunately it's a somewhat undocumented feature there. https://github.com/pjkersten/PlantUML/blob/master/extension.json shows the config parameter. Is there something similar for the diagrams extension to avoid the error above and what is the expected setting to get a local plantuml running?

**Comment by WolfgangFahl** [comment]
As a workaround i tried the script below which would help automating things a bit. Unfortunately the used shell exec is firejailed and won't allow the automatic download. So you have to run this script once manually from the shell and then it might work in the MediaWiki environment.

```bash
#!/bin/bash
# WF 2020-10-22
# invoke plantuml
#  plantuml version to use if not there yet
url=http://sourceforge.net/projects/plantuml/files/plantuml.1.2020.19.jar/download
# jar file to use
jarPath=/var/www/mediawiki/code/extensions/Diagrams
jar=$jarPath/plantuml.jar
tmp=/tmp/plantuml.log
# check if jar is available
if [ ! -f $jar ]
then
   #if not download it
   # allow writing of target path
   chmod g+w $jarPath
   echo "trying download of $jar " > $tmp
   wget $url -O $jar 2>&1 >> $tmp
   echo "$?" >> $tmp
fi
# pass on all arguments
/usr/bin/java $jar "$@"
```

**Comment by WolfgangFahl** [comment]
Unfortunately I end up with "Diagrams error:" and not further output but i assume i am closer ..

**Comment by WolfgangFahl** [comment]
```
Error occurred during initialization of VM
Could not reserve enough space for 256000KB object heap
```
was the error message - is that some shell restriction?

**Comment by WolfgangFahl** [comment]
the good old 
```php
$wgMaxShellMemory = 512000; 
```
is need here again ...

**Comment by WolfgangFahl** [comment]
Still we have 
```
ulimit
102400
```
why?

**Comment by WolfgangFahl** [comment]
https://serverfault.com/a/596765/162693?

**Comment by WolfgangFahl** [comment]
A binary search has shown I need at leat 
```bash
ulimit -v 3750000
```
to succesfully run plantuml. Even if i set 
```php
$wgMaxShellMemory = 4*1024*1024;
```
that doesn't help .. sigh

**Comment by WolfgangFahl** [comment]
Looks like the firejailes process can't access the true /tmp since it get's a fake tmp directory for it's own process.

**Comment by WolfgangFahl** [comment]
It is probably better to allow to configure a diagrams directory that is under control of mediawiki and whitelist that for firejail.

**Comment by WolfgangFahl** [comment]
The wrapping with @startuml/@enduml is missing ... is the plantuml script supposed to do this?

**Comment by WolfgangFahl** [comment]
For reference i tried
```bash
sudo port install plantuml
```
on my mac and inspected the plantuml script there. It contains
```bash
#!/bin/sh
  
# Is the location of the PlantUML launcher JAR file.
LAUNCHJAR="/opt/local/share/java/plantuml.jar"

exec java -jar "$LAUNCHJAR" "$@"
```

which is a very short version of my own debugging script.

**Comment by WolfgangFahl** [comment]
The current state of the debugging script is
```bash
#!/bin/bash
# WF 2020-10-22
# invoke plantuml
#  plantuml version to use if not there yet
url=http://sourceforge.net/projects/plantuml/files/plantuml.1.2020.19.jar/download
# jar file to use
jarPath=/var/www/mediawiki/code/extensions/Diagrams
jar=$jarPath/plantuml.jar


# create a log file
log=/tmp/plantuml.log
debug=true

clearlog() {
  if [ -f $log ]
  then
    rm $log
  fi
}

#
# log the given message
# param 1: msg - the message to log
#
dolog() {
  local l_msg="$1"
  echo "$l_msg" >> $log
}

# remove existing log if any
clearlog
# check if jar is available
if [ ! -f $jar ]
then
   #if not download it
   # allow writing of target path
   chmod g+w $jarPath
   dolog "trying download of $jar " 
   wget $url -O $jar 2>&1 >> $log
   dolog "wget return-code: $?" 
fi

# pass on all arguments
dolog "ulimit -a"
ulimit -a >> $log
dolog "/usr/bin/java -Djava.awt.headless=true -jar $jar $@" 
for var in "$@"
do
  dolog "param: $var"
  if [ -f $var ]
  then
     dolog "ls -l $var"
     ls -l $var >> $log
	   cat $var >> $log
     b=$(basename $var)
     # create a copy for inspection
     cp -p $var /tmp/$b.bak
  fi
done
# log run
/usr/bin/java -Djava.awt.headless=true -jar $jar "$@" >> $log 2>&1
# true run
/usr/bin/java -Djava.awt.headless=true -jar $jar "$@"
```

Which creates .bak copies of the input and shows that the plantuml process **is called three times** on each edit!

**Comment by samwilson** [comment]
Hopefully #101 will suffice for this.

(Sorry for the many-year delay.)
