### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by WolfgangFahl** [samwilson/diagrams-extension#26]
in class Dot
```
return "label=\"Diagrams error: mage not found: $imageName\"";
```

**Comment by samwilson** [comment]
Thanks!

Fixed in #27. I'll make a new release.

**Comment by WolfgangFahl** [comment]
Thx - i am working on the other issues today too. I'll get in touch via e-mail

**Comment by samwilson** [comment]
Thanks.

I'd prefer keeping discussion organized here in Github, or in Phabricator.
