### ISSUE TITLE
 Not working with img_auth.php

### ISSUE THREAD

**Issue by samwilson** [samwilson/diagrams-extension#61]
Bug reported at https://www.mediawiki.org/wiki/Topic:Wuj83a8ha1vvzw64

**Comment by YOUR1** [comment]
I wonder if this gets fixed when https://github.com/samwilson/diagrams-extension/pull/44 is merged

**Comment by akamuza** [comment]
Still not working. Version 0.12.0

**Comment by samwilson** [comment]
Thanks for opening #81 @YOUR1, and submitting the PR for it (#82).

However, I'm not quite sure that it's targeting the root cause of the issue. The differences between `getLocalRefPath()` and `getFullUrl()` are not going to fix this in the case of (for example) using a different storage backend (such as the AWS extension):

* `getLocalRefPath()`: `w/images/diagrams/Diagrams_49567a25087d4d341d3edcf3b9de2af6.cmapx`
* `getFullUrl()`: `http://localhost/w/img_auth.php/diagrams/Diagrams_49567a25087d4d341d3edcf3b9de2af6.cmapx`

In my testing it seems that this is more a configuration issue than anything that the extension can fix. The following `LocalSettings.php` config might be what you need:

```php
$wgUploadPath = "$wgScriptPath/img_auth.php";
$wgImgAuthUrlPathMap['/diagrams/'] = 'mwstore://local-backend/local-public/diagrams/';
```

**Comment by akamuza** [comment]
With this config line everything works as expected.

```
$wgImgAuthUrlPathMap['/diagrams/'] = 'mwstore://local-backend/local-public/diagrams/';
```

Thank you!

**Comment by samwilson** [comment]
Great!

I've updated the docs at https://www.mediawiki.org/wiki/Extension:Diagrams#Installation
