### ISSUE TITLE
Does not work with Mediawiki 1.33.0 or 1.33.1

### ISSUE THREAD

**Issue by WolfgangFahl** [samwilson/diagrams-extension#8]
To get the extension working i had to patch up to 1.33.2

**Comment by samwilson** [comment]
Sorry about the poor documentation with this!

With the new local-file uploading, I've increased the MediaWiki requirement to the latest current version of 1.34.0.

**Comment by WolfgangFahl** [comment]
@samwilson  thx for looking into this. How do we get the LTS version supported? I think supporting 1.31.7 would be important to attract more users to this extension. I my current enviornment LTS versions are mandatory.

**Comment by samwilson** [comment]
That's a good point, and normally I'd want to support the LTS version. But in this case, the extension is still experimental and hasn't released a stable version yet. Also, the next LTS release (1.35) is due out soon, and I think it makes most sense to support that, going forward. Once a 1.0.0 of the extension is released, it should thereafter always support all current versions of MediaWiki.

**Comment by WolfgangFahl** [comment]
for the svg support #13 i need to work with a 1.33.0 and it doesn't seem to send post request properly with the version from February. What is the incompatibility which i might need to work around to use e.g. the local rendering? 1.35 LTS is not out yet and probably to much work to get our 16+ extensions adapted.
