### ISSUE TITLE
Wrong version number reported

### ISSUE THREAD

**Issue by storkk** [samwilson/diagrams-extension#85]
Attempting to install the latest diagrams-extension using: 

1. the 0.12.2 release zip
2. the composer route
3. git clone

In the resulting [[System:Version]], all of the above report:
Extension	Version	Licence	Description	Authors
Diagrams	0.9.4 (a2d810f) 06:15, 28 October 2023	GPL-3.0-or-later	Render Graphviz, Mscgen, and PlantUML diagrams in wiki pages.	Sam Wilson

Expected version: 0.12.2. Not sure if this is just a typo in extension.json, or if something else is up

**Comment by samwilson** [comment]
Yep, just a typo! Fixed now. Thanks!
