### ISSUE TITLE
Diagrams::$commandFactory is deprecated

### ISSUE THREAD

**Issue by storkk** [samwilson/diagrams-extension#86]
Running a fresh install of MediaWiki 1.40.1 with PHP 8.2.7 (apache2handler), after installing the latest release of diagrams-extension (tried using git clone; unzip the release zip; using composer), I get the following message on each page:

Deprecated: Creation of dynamic property MediaWiki\Extension\Diagrams\Diagrams::$commandFactory is deprecated in <...>/Diagrams/includes/Diagrams.php on line 25

**Comment by samwilson** [comment]
Thanks! Fixed in #86.
