### ISSUE TITLE
PHP Notice:  Undefined index: map in /../w/extensions/Diagrams/includes/Diagrams.php on line 136

### ISSUE THREAD

**Issue by kghbln** [samwilson/diagrams-extension#96]
### Setup

- MediaWiki | 1.39.7 (64425c7)16:12, 15 May 2024
- PHP | 7.4.33 (apache2handler)
- MariaDB | 10.5.23-MariaDB-0+deb11u1
- - [Diagrams](https://www.mediawiki.org/wiki/Extension:Diagrams)	0.13.1

### Issue
On pages using PlantUML I get:
```
PHP Notice:  Undefined index: map in /../w/extensions/Diagrams/includes/Diagrams.php on line 136
Notice: Undefined index: map in /../w/extensions/Diagrams/includes/Diagrams.php on line 136
```

**Comment by samwilson** [comment]
Fixed in #101 (although I forgot to mention it in the commit message, oops!).
