### ISSUE TITLE
Making a template

### ISSUE THREAD

**Issue by keepersdungeon** [samwilson/diagrams-extension#98]
Is there a way to make a template out of the `<mermaid>{{{1}}}</mermaid>`?

**Comment by samwilson** [comment]
It should be possible to do this with the [#tag parser function](https://www.mediawiki.org/wiki/Help:Magic_words#Miscellaneous), e.g.:

```
{{#tag:mermaid | {{{1}}} }}
```

(If I'm understanding your question correctly.)

**Comment by keepersdungeon** [comment]
Yeah perfect thank you for your reply!
